### ISSUE TITLE
What about the other way around?

### ISSUE THREAD

**Issue by lblokland** [martindybal/taphome-homeassistant#120]
Would it be possible to access HA devices, and control them from TapHome?
I would like to use HA as a Zigbee gateway, because the support in TapHome is very limited.

Cheers!
Leon

**Comment by martindybal** [comment]
You can do that without this integration. You have to use http packet parser and Home Assistant api https://developers.home-assistant.io/docs/api/rest/

**Comment by martindybal** [comment]
You can use this. https://github.com/martindybal/taphome-homeassistant/wiki/Jak-přidat-Home-Assistant-zařízení-do-TapHome 

I apologize for the Czech, it's more convenient for most of the users.
