### ISSUE TITLE
config generator

### ISSUE THREAD

**Issue by Re4DeR** [martindybal/taphome-homeassistant#123]
Hi, config generator ( https://www.dybal.it/taphome-homeassistant/config-generator/  ) doesn't work. Frame with generated code is empty. Tested in Safari and Opera browser  on mac os.

**Comment by martindybal** [comment]
@Re4DeR can you provide me more information or screenshots? I try it on Safari on iPad and Opera on Windows. Both work for me.

**Comment by Re4DeR** [comment]
I cant, now it is working :D. In developer console there were error 404 on some .js files.  Now it is ok.

**Comment by martindybal** [comment]
@Re4DeR ok, that's weird. I'm using github pages as a hosting. Do you use some AdBlock? I'll close the issue. If the error repeats, feel free to reopen it and add more information.

**Comment by Re4DeR** [comment]
adblock yeap, but I turned it off for dybal.it.
