### ISSUE TITLE
Lights/Covers.. unavailable in home assistent

### ISSUE THREAD

**Issue by martinMMO** [martindybal/taphome-homeassistant#124]
Hello Martin,
 
my covers/blinds/termostats etc. doesn't work via home assistant. I can see all entities there, but they are unavailable.
My buttons work fine, for example when I have Dinner scene mapped on button, I can press it through home assistent (homekit too) and it works.

Do you have any idea why just my button works, what should I change ?

 <img width="100" alt="Screenshot 2022-12-27 at 07 54 40" src="https://user-images.githubusercontent.com/93922735/209625116-ff1bb096-6c13-4a3f-8776-929d21ac42d3.png"> <img width="100" alt="Screenshot 2022-12-27 at 07 55 46" src="https://user-images.githubusercontent.com/93922735/209625115-b85d533a-9b3f-44b3-8557-25f2c0b7f4e7.png" > <img width="80" alt="Screenshot 2022-12-27 at 08 07 25" src="https://user-images.githubusercontent.com/93922735/209626441-e956fd52-4115-4717-a595-f4aaeebc6398.png">

If any additional info is needed from me, pls let me know.

Thanks

**Comment by martindybal** [comment]
Hi, 
1. is there a log entry? 
1. What is the entity listing http://homeassistant.local:8123/config/entities? Aren't some entities there twice? 
1. What version of integration, Home Assistant and TapHome do you have?

**Comment by martinMMO** [comment]
1. Here is the [home-assistant.log](https://github.com/martindybal/taphome-homeassistant/files/10308744/home-assistant.log)
2. I don't see any duplicates <img width="2056" alt="Screenshot 2022-12-27 at 15 29 53" src="https://user-images.githubusercontent.com/93922735/209682141-aba6ad93-2d15-4b12-a008-d624126595ad.png">
3.  Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest
Integration version: 1.29.0
Taphome 2022.2.26560

I just thinking if my, for example, lights are configured correctly within taphome, when buttons works via home assistent but others entities not.. Example screenshots added below..



<img width="80" alt="Screenshot 2022-12-27 at 15 48 05" src="https://user-images.githubusercontent.com/93922735/209683130-86881040-7369-42fc-b85c-6495aa6cbf6e.png"> <img width="80" alt="Screenshot 2022-12-27 at 15 47 50" src="https://user-images.githubusercontent.com/93922735/209683149-345f6fac-cb06-4daa-bded-2c803480dff3.png"> <img width="80" alt="Screenshot 2022-12-27 at 15 47 35" src="https://user-images.githubusercontent.com/93922735/209683156-b08b889f-75e7-45ef-ad18-266d3f483c52.png">

**Comment by martindybal** [comment]
Integration should be 2021.3.1. Can you check it? How did you install it?

**Comment by martindybal** [comment]
Can you contact me via Messenger? https://www.facebook.com/Martin.Dybal/

**Comment by martinMMO** [comment]
The issue was probably related to HACS taphome installation. It was resolved by removing taphome files from HA and then manual installation (Copies the /custom_components/taphome/contents of the repository to the folder.)

Thanks Martin for your time, cooperation and support.

**Comment by martindybal** [comment]
It should be fixed by release 2023.1.0
