### ISSUE TITLE
Vitae support

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#14]
[Vitae](https://www.vitaelight.com) is 3 in 1 light control by turning on and off again. HomeAssitant don’t have a support for this type of light in [Light Entity](https://developers.home-assistant.io/docs/core/entity/light). I don’t have better idea than connected it as three independent lights. I don`t want to create own entity. But there will be few limitations. You can turn on more than one light at time and you have to wait 11seconds to change state. Maybe 

Maybe @polcape has better idea how to integrate Vitae? Is theree. A way how to specify only some (3) colors. for color light?

**Comment by polcape** [comment]
I think that the only way for controlling in HA the lamp color is by automation on output connected to the lamp.

So we have 4 object: 
 - real output connected to lamp
 - virtual switch for orange
 - virtual switch for warm white
 - virtual switch for cold white

If I want orange:
 - real output off for more than 11 seconds and then real output on

If I want warm white:
 - real output off for more than 11 seconds and then real output on, real output off, eal output on

If I cold white:
 - real output off for more than 11 seconds and then real output on, real output off, eal output on, real output off, eal output on

Can be a solution?

**Comment by martindybal** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/flux/switch.py there is a code samle for set device by entity id
