### ISSUE TITLE
Core crash when try setup HueBrightness

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#19]
When I try setup `HueBrightness` I got server internal error 500 and Core is restarted

`curl -X POST "https://cloudapi.taphome.com/api/CloudApi/v1/setDeviceValue" -H  "accept: application/json" -H  "Authorization: TapHome 242d6050-bc5d-4d99-b46c-83d5aa9a0696" -H  "Content-Type: application/json" -d "{  'deviceId': 1,  'values': [{'valueTypeId': 48, 'value': 1}, {'valueTypeId': 65, 'value': 50}]}"`

Token is for demo account. DeviceId 1 is RGB-1

**Comment by martindybal** [comment]
Value should be less or equal to 1. But I think API should handle this by validation.

**Comment by polcape** [comment]
API don't validate the value and after set 50 the app show brightness to 5000%

**Comment by martindybal** [comment]
I was not able to reproduce it on my Core, only on demo account

**Comment by martindybal** [comment]
I reported this to TapHome team they should fix this in 2021.1
