### ISSUE TITLE
Status of light not syncronized

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#22]
When I power on a RGB light in Home Assistant the light power on also in TapHome system with last setted value (for example color yellow and brightness 50%), but in Home Assistant the status is brightness 0% and color red.
If I set other value in HA then the status on TapHome is changing correctly.

Also when I power on light in TapHome the light in HA is still powered off.

I think this was related to this issue
https://github.com/martindybal/taphome-homeassistant/issues/4

**Comment by martindybal** [comment]
Yes it's caused missing TapHome support for fetching changes. It should be implemented soon.

**Comment by martindybal** [comment]
I added polling as temporary workaround.
