### ISSUE TITLE
Handle cloud api errors

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#36]
Unexpected error states is not handle now. This issue should collect possible unexpected states

**Comment by martindybal** [comment]
`{'type': 'https://tools.ietf.org/html/rfc7231#section-6.6.1', 'title': 'An error occured while processing your request.', 'status': 500, 'detail': 'HandleGetDeviceValue: server error: ServiceUnavailable (503): Exception: Connection was closed before response was received.', 'traceId': '00-7958e170df4ccb48a4ce904107a249db-b33f59d4ce522349-00'}`

**Comment by martindybal** [comment]
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.6.1', 'title': 'An error occured while processing your request.', 'status': 500, 'detail': 'HandleGetDeviceValue: server error: NotFound (404): Core not connected to service connection.', 'traceId': '00-c5fcbe15520af045a0e5e3e6f924acd3-162eca020e6c2b46-00'}

**Comment by martindybal** [comment]
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.6.1', 'title': 'An error occured while processing your request.', 'status': 500, 'detail': 'HandleGetDeviceValue: server error: The operation was canceled.', 'traceId': '00-042a5c61672b4643be5941d10d91591e-fd6c2560fd72f144-00'}

**Comment by martindybal** [comment]
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.4', 'title': 'Not Found', 'status': 404, 'detail': 'HandleDiscovery: server error: Location 0ba2fb0d-9374-4bb5-a4c0-51cf4203d1a0 is offline', 'traceId': '00-6dc7df3a10805048bddc54373958e47c-f21003df11ca204e-00'}

**Comment by martindybal** [comment]
{'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.3', 'title': 'Forbidden', 'status': 403, 'detail': "HandleGetDeviceValue: Device doesn't exist anymore", 'traceId': '00-a60e338aa1001a42abe11128c91a6bb1-441c64d0283b1345-00'}

**Comment by polcape** [comment]
Hi,

sometimes when I restart HA instance taphome integration fails, so entities are not loaded.

When happens I try to contact API in manual mode and  I get this answer

{"title":"WebApiClientException HTTP API Client error ServiceUnavailable (503) fn: HandleGetDeviceValue","status":503,"detail":"Exception: One or more errors occurred. (WebSocket connection is down.) loc=a691840b-3060-45de-ad91-b5e97fd1cedd","traceId":"00-9dca8332cc700a47a7102d4c59eb3a01-4fb9ea768f609246-00"}

I ask to TapHome support how works and this is the answer

> this means that you have successfully connected to the cloud api, it has chosen which cloud tunnel to go through, and the tunnel has sent a message and during the sending it was found that the connection to the core is invalid / closed. it will be restored, maybe 5 maybe in 20 seconds, only until then timeout connection cloud api → tunnel and also connection core → cloud api. now what about that .. I can try another tunnel if it's not too late. if we spend more than 20 seconds getting the answer, it will make the core → cloud api connection and even if we have the answer it will not wait for it. according to us you should just try to call the cloud api again in a minute, because the internet connection is not 100%

So, to avoid the problem I think that the integration could retry the connection after few seconds before fail.
