### ISSUE TITLE
Error token

### ISSUE THREAD

**Issue by Erzo-github** [martindybal/taphome-homeassistant#38]
Zobral som so sebou raspi 4 mimo domova a prestalo fungovat. Priamy link funguje bez problemov. 
![error 3](https://user-images.githubusercontent.com/75236559/102697746-71d02400-4238-11eb-9760-0b55ec306894.JPG)

**Comment by martindybal** [comment]
Konfigurace se změnila #30. Je potřeba přidat sekci `cores`
