### ISSUE TITLE
Sensor with too decimals

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#45]
To avoid this behavoir it could be useful limit the number of decimal in a float number.

![image](https://user-images.githubusercontent.com/3648038/103176067-2ee10280-486f-11eb-98ba-631a6d6dcb6f.png)

**Comment by martindybal** [comment]
That's good point. It didn't happen to me on my virtual device :)

**Comment by martindybal** [comment]
@polcape I round temperature and humidity to one decimal place

**Comment by polcape** [comment]
I use round also for electric demand https://github.com/martindybal/taphome-homeassistant/commit/d982a3da249891b72d093867c09ae6394c5c550f
