### ISSUE TITLE
Add brightness sensor

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#48]
@polcape add brightness sensor in #44 but api returns only percentage value. I have information from Michal Dobrodenka thet they want to add lm value to api. We should use lm instead of percentage.

**Comment by polcape** [comment]
Yes, brightness is only in % in taphome
Have it in lm or lx will be more useful.

**Comment by martindybal** [comment]
This is only official brightness sensor for TapHome https://taphome.com/en/wind-brightness-temperature-sensor so we can use it as reference device and calculate value from 100kLux for now. And than use new api value.

**Comment by polcape** [comment]
It say Sunshine intensity in percent with one percent for each kLux, measurement range 0.8 – 100kLux
So you propose 1%=1000 lux and 100% 100000 lux?

**Comment by martindybal** [comment]
Yes, you can simply use `100_000 * value`

**Comment by polcape** [comment]
I fixed
