### ISSUE TITLE
TapHomeVariable value should be number

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#50]
Now it's look like a string value 
![image](https://user-images.githubusercontent.com/7644099/103281292-c1e67d80-49d2-11eb-8e52-7415043090a5.png)

I don't know how to say HA that value is int. I can't use `unit_of_measurement`

**Comment by polcape** [comment]
I think only way to tell to HA that is a number is add unit_of_measurement, and in this way you see a graph in history and not the bar like that

**Comment by martindybal** [comment]
@polcape I got it :) 
![image](https://user-images.githubusercontent.com/7644099/103290834-b901a600-49ea-11eb-98e2-69446b535717.png)

 related with https://github.com/home-assistant/architecture/issues/478
