### ISSUE TITLE
Termostat + switch

### ISSUE THREAD

**Issue by Erzo-github** [martindybal/taphome-homeassistant#51]
![kurenie 1](https://user-images.githubusercontent.com/75236559/103476490-8d016e80-4db6-11eb-8018-53cb5779d54c.JPG)

**Comment by Erzo-github** [comment]
![kurenie 2](https://user-images.githubusercontent.com/75236559/103476631-dc946a00-4db7-11eb-97c8-83a3255fc521.JPG)

**Comment by martindybal** [comment]
Some users can use only switch for heating or cooling not multivalue switch. 

My proposal: 
```
- thermostat: 1
  hvac_mode: 2
  heat: 3
  cool: 4 
```
where heat and cool are switchs and you can't combine `hvac_mode` with `cool`or `heat`

**Comment by martindybal** [comment]
I realized that we can't combine two switch 'cool' and 'heat'. They both can be on in TapHome
