### ISSUE TITLE
Integration is not loaded correctly

### ISSUE THREAD

**Issue by martindybal** [martindybal/taphome-homeassistant#66]
Hi,

sometimes when I restart HA instance taphome integration fails, so entities are not loaded.

When happens I try to contact API in manual mode and  I get this answer

{"title":"WebApiClientException HTTP API Client error ServiceUnavailable (503) fn: HandleGetDeviceValue","status":503,"detail":"Exception: One or more errors occurred. (WebSocket connection is down.) loc=a691840b-3060-45de-ad91-b5e97fd1cedd","traceId":"00-9dca8332cc700a47a7102d4c59eb3a01-4fb9ea768f609246-00"}

I ask to TapHome support how works and this is the answer

> this means that you have successfully connected to the cloud api, it has chosen which cloud tunnel to go through, and the tunnel has sent a message and during the sending it was found that the connection to the core is invalid / closed. it will be restored, maybe 5 maybe in 20 seconds, only until then timeout connection cloud api → tunnel and also connection core → cloud api. now what about that .. I can try another tunnel if it's not too late. if we spend more than 20 seconds getting the answer, it will make the core → cloud api connection and even if we have the answer it will not wait for it. according to us you should just try to call the cloud api again in a minute, because the internet connection is not 100%

So, to avoid the problem I think that the integration could retry the connection after few seconds before fail.

_Originally posted by @polcape in https://github.com/martindybal/taphome-homeassistant/issues/36#issuecomment-778035040_

**Comment by martindybal** [comment]
@polcape I created a own issue for this.

This'll be quiet complicated. If HA integration don't load in ten seconds user get warning. If HA integration didn't load in 60s HA kill it. So we can't try it again later.    

We need information from `discover` to start we don't have necessary  information in config. I can create HA entity without name. 

I didn't see any other way than reimplement the configuration. We can add UI for configuration #10 or we can prepare custom tool for generate config (Simple web app) which'll load `discover` and save it to configuration. Problem for both is we'll not know about changes in `discover`.

I suggest wait for a local api support from TapHome

**Comment by polcape** [comment]
Hi @martindybal ,
thanks.

The specific problem 503 "WebSocket connection is down" was releated to the tunnel from my core to cloud not correctly setted.
After a reboot of core all come back online.

Yes, I agree with you. The solution is wait local api

**Comment by martindybal** [comment]
@polcape we found a bug in TapHome cloudapi server. It should be fixed!

**Comment by polcape** [comment]
Good news!
