### ISSUE TITLE
Can't adjust temperature on thermostat

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#68]
From some days I can't adjust temperature on thermostat.

Something change on HA or TapHome API?

![image](https://user-images.githubusercontent.com/3648038/112753027-477bc880-8fd6-11eb-811e-7d6be1de2aeb.png)

**Comment by martindybal** [comment]
It's look like that TapHome change ValueType from `DesiredTemperature` to new `AnalogOutputDesiredValue`. I have to ask TapHome team why they do that.

**Comment by martindybal** [comment]
There is one more change. Api lost infomrations about min and max temperature. I can use some default, but what value should it have? Maybe another configuration... :-(

**Comment by polcape** [comment]
Oh...I think we have to insert in in configuration, maybe with default value that can be overwrited.

**Comment by martindybal** [comment]
TapHome fix it!

**Comment by polcape** [comment]
Great news!
