### ISSUE TITLE
Problem nacitat min+max termostat

### ISSUE THREAD

**Issue by Erzo-github** [martindybal/taphome-homeassistant#70]
![climate](https://user-images.githubusercontent.com/75236559/114311210-13cc9280-9aee-11eb-9ad3-bb3ecbe9725a.JPG)

**Comment by polcape** [comment]
I think it's connected to this https://github.com/martindybal/taphome-homeassistant/issues/68

TapHome change the json reply for thermostat

**Comment by martindybal** [comment]
Yes, it's TapHome bug or ugly feature :(. We can add min max into configuration. But we don't have any configuration now. So it's not so easy to add that.

**Comment by martindybal** [comment]
TapHome fix it!
